In [2]:
import numpy as np

# 1. Scalar Tensor
scalar = np.array(10)

print("Scalar Tensor:")
print("Value:", scalar)
print("Shape:", scalar.shape)
print("Dimensions:", scalar.ndim)
print()

# 2. Vector Tensor
vector = np.array([1, 2, 3, 4, 5])

print("Vector Tensor:")
print("Value:", vector)
print("Shape:\n", vector.shape)
print("Dimensions:", vector.ndim)
print()

# 3. 3x3 Matrix Tensor
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Matrix Tensor (3x3):")
print("Value:\n", matrix)
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print()

# 4. 3D Tensor of shape (2,3,4)
tensor3d = np.arange(24).reshape(2, 3, 4)

print("3D Tensor (2x3x4):")
print("Value:\n", tensor3d)
print("Shape:", tensor3d.shape)
print("Dimensions:", tensor3d.ndim)

Scalar Tensor:
Value: 10
Shape: ()
Dimensions: 0

Vector Tensor:
Value: [1 2 3 4 5]
Shape:
 (5,)
Dimensions: 1

Matrix Tensor (3x3):
Value:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2

3D Tensor (2x3x4):
Value:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Shape: (2, 3, 4)
Dimensions: 3


In [1]:
import numpy as np

# 1. Random tensor of shape (3,3)
tensor_3x3 = np.random.rand(3, 3)
print("Random Tensor (3x3):")
print(tensor_3x3)
print()

# 2. Random tensor of shape (4,4)
tensor_4x4 = np.random.rand(4, 4)
print("Random Tensor (4x4):")
print(tensor_4x4)
print()

# 3. Random 3D tensor of shape (2,3,3)
tensor_3d = np.random.rand(2, 3, 3)
print("Random 3D Tensor (2x3x3):")
print(tensor_3d)

Random Tensor (3x3):
[[0.8568261  0.62205525 0.7095991 ]
 [0.11795633 0.9588025  0.43742197]
 [0.36753147 0.91800215 0.90791288]]

Random Tensor (4x4):
[[0.81532328 0.91252158 0.24899078 0.44293457]
 [0.61205022 0.47824744 0.32705199 0.7498834 ]
 [0.61918508 0.39519696 0.32062957 0.19108792]
 [0.99254443 0.19371256 0.89512893 0.17199039]]

Random 3D Tensor (2x3x3):
[[[4.76079909e-01 5.99081257e-01 6.55778794e-01]
  [2.70427423e-01 7.02627589e-01 2.91872845e-01]
  [2.25767953e-01 1.60018113e-01 8.58731056e-01]]

 [[7.99672390e-01 7.04558358e-01 3.27945087e-01]
  [4.73577819e-01 3.55977079e-04 9.14743745e-01]
  [1.83708598e-02 2.96599242e-01 9.90543435e-01]]]


In [2]:
import numpy as np

# Create the tensor
tensor = np.array([
    [[1,2,3],
     [4,5,6]],

    [[7,8,9],
     [10,11,12]]
])

# 1. Print the first matrix
print("First matrix:")
print(tensor[0])

# 2. Print the second matrix
print("\nSecond matrix:")
print(tensor[1])

# 3. Print the element 5
print("\nElement 5:")
print(tensor[0, 1, 1])

# 4. Print the last element
print("\nLast element:")
print(tensor[1, 1, 2])

# 5. Print the first row of the first matrix
print("\nFirst row of the first matrix:")
print(tensor[0, 0])

First matrix:
[[1 2 3]
 [4 5 6]]

Second matrix:
[[ 7  8  9]
 [10 11 12]]

Element 5:
5

Last element:
12

First row of the first matrix:
[1 2 3]


In [3]:
import numpy as np

# Create tensors
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# 1. Tensor Addition
addition = A + B
print("Tensor Addition:\n", addition)

# 2. Tensor Subtraction
subtraction = A - B
print("\nTensor Subtraction:\n", subtraction)

# 3. Element-wise Multiplication
elementwise_mul = A * B
print("\nElement-wise Multiplication:\n", elementwise_mul)

# 4. Matrix Multiplication
matrix_mul = np.matmul(A, B)
print("\nMatrix Multiplication:\n", matrix_mul)

# 5. Element-wise Division
division = A / B
print("\nElement-wise Division:\n", division)

Tensor Addition:
 [[ 6  8]
 [10 12]]

Tensor Subtraction:
 [[-4 -4]
 [-4 -4]]

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]

Matrix Multiplication:
 [[19 22]
 [43 50]]

Element-wise Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [4]:
import numpy as np

# Create tensor
tensor = np.arange(24)
print("Original Tensor (24,):")
print(tensor)
print("Shape:", tensor.shape)

# 1. Reshape to (4,6)
tensor_4x6 = tensor.reshape(4,6)
print("\nReshaped to (4,6):")
print(tensor_4x6)
print("Shape:", tensor_4x6.shape)

# 2. Reshape to (2,3,4)
tensor_2x3x4 = tensor.reshape(2,3,4)
print("\nReshaped to (2,3,4):")
print(tensor_2x3x4)
print("Shape:", tensor_2x3x4.shape)

# 3. Convert back to (24,)
tensor_back = tensor_2x3x4.reshape(24,)
print("\nConverted back to (24,):")
print(tensor_back)
print("Shape:", tensor_back.shape)

# 4. Transpose the (4,6) tensor
transpose_tensor = tensor_4x6.T
print("\nTranspose of (4,6) tensor:")
print(transpose_tensor)
print("Shape:", transpose_tensor.shape)

Original Tensor (24,):
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Shape: (24,)

Reshaped to (4,6):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Shape: (4, 6)

Reshaped to (2,3,4):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Shape: (2, 3, 4)

Converted back to (24,):
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Shape: (24,)

Transpose of (4,6) tensor:
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]
Shape: (6, 4)


In [5]:
import numpy as np

# Create vectors
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 1. Stack them vertically
vertical_stack = np.vstack((a, b))
print("Vertical Stack:")
print(vertical_stack)

# 2. Stack them horizontally
horizontal_stack = np.hstack((a, b))
print("\nHorizontal Stack:")
print(horizontal_stack)

# 3. Combine them into a 2x3 matrix
matrix_2x3 = np.array([a, b])
print("\n2x3 Matrix:")
print(matrix_2x3)

Vertical Stack:
[[1 2 3]
 [4 5 6]]

Horizontal Stack:
[1 2 3 4 5 6]

2x3 Matrix:
[[1 2 3]
 [4 5 6]]


In [21]:
import numpy as np

# Create RGB image tensor
image = np.random.randint(0, 255, (224, 224, 3))

# 1. Print the tensor shape
print("Image Shape:", image.shape)

# 2. Extract the Red channel
red_channel = image[:, :, 0]
print("\nRed Channel Shape:", red_channel.shape)

# 3. Extract the Green channel
green_channel = image[:, :, 1]
print("\nGreen Channel Shape:", green_channel.shape)

# 4. Extract the Blue channel
blue_channel = image[:, :, 2]
print("\nBlue Channel Shape:", blue_channel.shape)

# 5. Convert to grayscale (average of channels)
grayscale = image.mean(axis=2)

print("\nGrayscale Image Shape:", grayscale.shape)
print("\nGrayscale Tensor:")
print(grayscale)

Image Shape: (224, 224, 3)

Red Channel Shape: (224, 224)

Green Channel Shape: (224, 224)

Blue Channel Shape: (224, 224)

Grayscale Image Shape: (224, 224)

Grayscale Tensor:
[[168.66666667  63.66666667 207.         ... 136.33333333 119.33333333
  157.        ]
 [114.          70.         169.66666667 ...  28.         118.
  102.33333333]
 [202.66666667 151.          72.66666667 ... 162.66666667 222.66666667
   91.33333333]
 ...
 [116.66666667 111.         224.33333333 ... 112.66666667  76.33333333
  175.        ]
 [149.          71.33333333 132.         ...  61.         176.
  162.66666667]
 [114.66666667 138.33333333 118.33333333 ...  95.         146.33333333
  125.33333333]]


In [11]:
import numpy as np

# Create tensor
data = np.random.randint(1, 100, (5,5))
print("Tensor:\n", data)

# 1. Mean
mean_val = data.mean()
print("\nMean:", mean_val)

# 2. Maximum value
max_val = data.max()
print("Maximum value:", max_val)

# 3. Minimum value
min_val = data.min()
print("Minimum value:", min_val)

# 4. Sum of all elements
sum_val = data.sum()
print("Sum of all elements:", sum_val)

# 5. Standard deviation
std_val = data.std()
print("Standard Deviation:", std_val)

Tensor:
 [[72 98 71  7 84]
 [14 62 26 22 50]
 [53 31 47  2 25]
 [10 49 26 83 35]
 [21 95  4 66 11]]

Mean: 42.56
Maximum value: 98
Minimum value: 2
Sum of all elements: 1064
Standard Deviation: 29.126043328952186


In [12]:
import numpy as np

# 1. Create a 4D tensor with random numbers
tensor_4d = np.random.rand(2, 3, 4, 5)  # Random decimals between 0 and 1

# 2. Print tensor details
print("Tensor:\n", tensor_4d)
print("\nShape:", tensor_4d.shape)
print("Number of dimensions:", tensor_4d.ndim)
print("Total number of elements:", tensor_4d.size)

Tensor:
 [[[[0.20434361 0.42725184 0.79278493 0.2240604  0.54897552]
   [0.18726953 0.26409978 0.93890768 0.23957223 0.28242015]
   [0.33761224 0.59263762 0.98819964 0.92360531 0.85616552]
   [0.24415845 0.90365926 0.13557679 0.5542961  0.12560379]]

  [[0.36108056 0.99201973 0.76091064 0.50325624 0.72201087]
   [0.45267697 0.7941832  0.40533733 0.90652272 0.39861118]
   [0.02665099 0.08615557 0.48638412 0.98874704 0.741454  ]
   [0.6722053  0.1150102  0.11504682 0.28179547 0.52983156]]

  [[0.09483032 0.29704586 0.37971959 0.15147273 0.55746033]
   [0.68335858 0.34039759 0.73675604 0.06258489 0.71132831]
   [0.04957119 0.01219099 0.9788861  0.0789456  0.74320479]
   [0.99578115 0.78908688 0.56913561 0.08086521 0.23546209]]]


 [[[0.52368495 0.73152522 0.18769483 0.46035853 0.78273702]
   [0.62126247 0.47642452 0.82447499 0.33145479 0.16411552]
   [0.04828298 0.38167032 0.92148525 0.42351138 0.9589951 ]
   [0.73104244 0.25321709 0.68295873 0.22172715 0.45049526]]

  [[0.82570228 0.6351

In [13]:
import numpy as np

# Create the tensor
tensor = np.arange(60).reshape(3,4,5)
print("Tensor:\n", tensor)

# 1. Print the first 2D matrix
print("\nFirst 2D matrix:")
print(tensor[0])

# 2. Print the last 2D matrix
print("\nLast 2D matrix:")
print(tensor[-1])

# 3. Extract the second row from every matrix
second_row = tensor[:, 1, :]
print("\nSecond row from every matrix:")
print(second_row)

# 4. Extract the last column from every matrix
last_column = tensor[:, :, -1]
print("\nLast column from every matrix:")
print(last_column)

# 5. Extract a sub-tensor containing the first two matrices
sub_tensor = tensor[:2, :, :]
print("\nSub-tensor with first two matrices:")
print(sub_tensor)

Tensor:
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]

First 2D matrix:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Last 2D matrix:
[[40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]

Second row from every matrix:
[[ 5  6  7  8  9]
 [25 26 27 28 29]
 [45 46 47 48 49]]

Last column from every matrix:
[[ 4  9 14 19]
 [24 29 34 39]
 [44 49 54 59]]

Sub-tensor with first two matrices:
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]


In [14]:
import numpy as np

# Create tensor
tensor = np.arange(48)
print("Original Tensor (1D):")
print(tensor)
print("Shape:", tensor.shape)

# 1. Reshape to (6,8)
tensor_6x8 = tensor.reshape(6,8)
print("\nReshaped to (6,8):")
print(tensor_6x8)
print("Shape:", tensor_6x8.shape)

# 2. Reshape to (4,4,3)
tensor_4x4x3 = tensor.reshape(4,4,3)
print("\nReshaped to (4,4,3):")
print(tensor_4x4x3)
print("Shape:", tensor_4x4x3.shape)

# 3. Reshape to (2,3,4,2)
tensor_2x3x4x2 = tensor.reshape(2,3,4,2)
print("\nReshaped to (2,3,4,2):")
print(tensor_2x3x4x2)
print("Shape:", tensor_2x3x4x2.shape)

# 4. Flatten the tensor back to 1D
tensor_flat = tensor_2x3x4x2.reshape(-1)
print("\nFlattened back to 1D:")
print(tensor_flat)
print("Shape:", tensor_flat.shape)

Original Tensor (1D):
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]
Shape: (48,)

Reshaped to (6,8):
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]]
Shape: (6, 8)

Reshaped to (4,4,3):
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]
Shape: (4, 4, 3)

Reshaped to (2,3,4,2):
[[[[ 0  1]
   [ 2  3]
   [ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]
   [12 13]
   [14 15]]

  [[16 17]
   [18 19]
   [20 21]
   [22 23]]]


 [[[24 25]
   [26 27]
   [28 29]
   [30 31]]

  [[32 33]
   [34 35]
   [36 37]
   [38 39]]

  [[40 41]
   [42 43]
   [44 45]
   [46 47]]]]
Shape: (2, 3, 4, 2)

Flattened back to 1D:
[ 0  1  2  3  4  5  

In [15]:
import numpy as np

# Create tensors
A = np.ones((3,3))
B = np.zeros((3,3))

# 1. Concatenate row-wise (stack B below A)
row_concat = np.vstack((A, B))
print("Row-wise Concatenation:")
print(row_concat)
print("Shape:", row_concat.shape)

# 2. Concatenate column-wise (stack B to the right of A)
col_concat = np.hstack((A, B))
print("\nColumn-wise Concatenation:")
print(col_concat)
print("Shape:", col_concat.shape)

# 3. Stack them to create a 3D tensor
stack_3d = np.stack((A, B), axis=0)  # Axis 0 adds a new dimension
print("\nStacked 3D Tensor:")
print(stack_3d)
print("Shape:", stack_3d.shape)

Row-wise Concatenation:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape: (6, 3)

Column-wise Concatenation:
[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]
Shape: (3, 6)

Stacked 3D Tensor:
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
Shape: (2, 3, 3)


In [16]:
import numpy as np

# Create tensor
tensor = np.arange(24).reshape(6,4)
print("Original Tensor:\n", tensor)

# 1. Split the tensor into two equal parts (along rows)
split_two = np.array_split(tensor, 2, axis=0)
print("\nSplit into two equal parts:")
for i, part in enumerate(split_two):
    print(f"Part {i+1}:\n", part)

# 2. Split the tensor into three parts (along rows)
split_three = np.array_split(tensor, 3, axis=0)
print("\nSplit into three parts:")
for i, part in enumerate(split_three):
    print(f"Part {i+1}:\n", part)

# 3. Extract the first three rows
first_three_rows = tensor[:3, :]
print("\nFirst three rows:\n", first_three_rows)

# 4. Extract the last column
last_column = tensor[:, -1]
print("\nLast column:\n", last_column)

Original Tensor:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

Split into two equal parts:
Part 1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Part 2:
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

Split into three parts:
Part 1:
 [[0 1 2 3]
 [4 5 6 7]]
Part 2:
 [[ 8  9 10 11]
 [12 13 14 15]]
Part 3:
 [[16 17 18 19]
 [20 21 22 23]]

First three rows:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Last column:
 [ 3  7 11 15 19 23]


In [17]:
import numpy as np

# 1. Create the tensor
tensor = np.random.randint(1, 10, (3, 4, 2))
print("Original Tensor:\n", tensor)
print("Shape:", tensor.shape)

# 2. Transpose the tensor
transposed = tensor.transpose()  # reverses the axes by default
print("\nTransposed Tensor:\n", transposed)
print("Shape:", transposed.shape)

# 3. Swap axes 0 and 2
swap_0_2 = np.swapaxes(tensor, 0, 2)
print("\nTensor after swapping axes 0 and 2:\n", swap_0_2)
print("Shape:", swap_0_2.shape)

# 4. Swap axes 1 and 2
swap_1_2 = np.swapaxes(tensor, 1, 2)
print("\nTensor after swapping axes 1 and 2:\n", swap_1_2)
print("Shape:", swap_1_2.shape)

Original Tensor:
 [[[7 2]
  [1 4]
  [2 5]
  [1 6]]

 [[7 5]
  [6 7]
  [4 8]
  [1 4]]

 [[1 9]
  [9 1]
  [1 4]
  [5 8]]]
Shape: (3, 4, 2)

Transposed Tensor:
 [[[7 7 1]
  [1 6 9]
  [2 4 1]
  [1 1 5]]

 [[2 5 9]
  [4 7 1]
  [5 8 4]
  [6 4 8]]]
Shape: (2, 4, 3)

Tensor after swapping axes 0 and 2:
 [[[7 7 1]
  [1 6 9]
  [2 4 1]
  [1 1 5]]

 [[2 5 9]
  [4 7 1]
  [5 8 4]
  [6 4 8]]]
Shape: (2, 4, 3)

Tensor after swapping axes 1 and 2:
 [[[7 1 2 1]
  [2 4 5 6]]

 [[7 6 4 1]
  [5 7 8 4]]

 [[1 9 1 5]
  [9 1 4 8]]]
Shape: (3, 2, 4)


In [18]:
import numpy as np

# Create tensor
tensor = np.random.randint(1, 100, (4,5,3))
print("Tensor:\n", tensor)
print("Shape:", tensor.shape)

# 1. Mean of the entire tensor
mean_total = tensor.mean()
print("\nMean of entire tensor:", mean_total)

# 2. Mean along axis 0 (across the 4 matrices)
mean_axis0 = tensor.mean(axis=0)
print("\nMean along axis 0:\n", mean_axis0)
print("Shape:", mean_axis0.shape)

# 3. Mean along axis 1 (across the 5 rows in each matrix)
mean_axis1 = tensor.mean(axis=1)
print("\nMean along axis 1:\n", mean_axis1)
print("Shape:", mean_axis1.shape)

# 4. Maximum values in the tensor
max_val = tensor.max()
print("\nMaximum value in tensor:", max_val)

# 5. Minimum values in the tensor
min_val = tensor.min()
print("Minimum value in tensor:", min_val)

# 6. Standard deviation
std_val = tensor.std()
print("Standard deviation:", std_val)

Tensor:
 [[[86 20 13]
  [69 38 79]
  [81 89 95]
  [84 50 29]
  [99 42 93]]

 [[34 51 47]
  [84 31 64]
  [18 70 56]
  [44 51 66]
  [48 68 19]]

 [[29 57 31]
  [19 74 35]
  [27  6 20]
  [17 28 31]
  [38 86 29]]

 [[83  4 17]
  [76 41 22]
  [77 22 52]
  [54 83 96]
  [27  7 11]]]
Shape: (4, 5, 3)

Mean of entire tensor: 48.61666666666667

Mean along axis 0:
 [[58.   33.   27.  ]
 [62.   46.   50.  ]
 [50.75 46.75 55.75]
 [49.75 53.   55.5 ]
 [53.   50.75 38.  ]]
Shape: (5, 3)

Mean along axis 1:
 [[83.8 47.8 61.8]
 [45.6 54.2 50.4]
 [26.  50.2 29.2]
 [63.4 31.4 39.6]]
Shape: (4, 3)

Maximum value in tensor: 99
Minimum value in tensor: 4
Standard deviation: 27.233613829644835


In [19]:
import numpy as np

# Create tensor
tensor = np.random.randint(1, 50, (5,5))
print("Original Tensor:\n", tensor)

# 1. Extract all values greater than 25
greater_than_25 = tensor[tensor > 25]
print("\nValues greater than 25:\n", greater_than_25)

# 2. Replace values less than 10 with 0
tensor[tensor < 10] = 0
print("\nTensor after replacing values < 10 with 0:\n", tensor)

# 3. Count how many values are greater than 30
count_gt_30 = np.sum(tensor > 30)
print("\nNumber of values greater than 30:", count_gt_30)

# 4. Find indices where values are greater than 40
indices_gt_40 = np.argwhere(tensor > 40)
print("\nIndices where values are greater than 40:\n", indices_gt_40)

Original Tensor:
 [[30  9 12 36 31]
 [ 9 36 13 42 37]
 [ 1 34 13  9  3]
 [10 17 31 37 25]
 [22 29 39 19 46]]

Values greater than 25:
 [30 36 31 36 42 37 34 31 37 29 39 46]

Tensor after replacing values < 10 with 0:
 [[30  0 12 36 31]
 [ 0 36 13 42 37]
 [ 0 34 13  0  0]
 [10 17 31 37 25]
 [22 29 39 19 46]]

Number of values greater than 30: 10

Indices where values are greater than 40:
 [[1 3]
 [4 4]]


In [22]:
import numpy as np

# Create tensor
tensor = np.arange(16).reshape(4,4)
print("Original Tensor:\n", tensor)

# 1. Flip the tensor horizontally (left-right)
flip_horizontal = np.fliplr(tensor)
print("\nHorizontally Flipped Tensor:\n", flip_horizontal)

# 2. Flip the tensor vertically (up-down)
flip_vertical = np.flipud(tensor)
print("\nVertically Flipped Tensor:\n", flip_vertical)

# 3. Rotate the tensor 90 degrees clockwise
rotate_90 = np.rot90(tensor, k=-1)  # k=-1 rotates clockwise
print("\nRotated 90 degrees clockwise:\n", rotate_90)

# 4. Rotate the tensor 180 degrees
rotate_180 = np.rot90(tensor, k=2)
print("\nRotated 180 degrees:\n", rotate_180)

Original Tensor:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Horizontally Flipped Tensor:
 [[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]

Vertically Flipped Tensor:
 [[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]

Rotated 90 degrees clockwise:
 [[12  8  4  0]
 [13  9  5  1]
 [14 10  6  2]
 [15 11  7  3]]

Rotated 180 degrees:
 [[15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [23]:
import numpy as np

# 1. Identity matrix of size 5x5
identity_matrix = np.eye(5)
print("Identity Matrix (5x5):\n", identity_matrix)

# 2. Tensor filled with all 7s (4x4)
tensor_sevens = np.full((4,4), 7)
print("\nTensor filled with 7s (4x4):\n", tensor_sevens)

# 3. Diagonal matrix with values [1,2,3,4]
diag_matrix = np.diag([1,2,3,4])
print("\nDiagonal Matrix with [1,2,3,4]:\n", diag_matrix)

# 4. Tensor with values from 10 to 100 with step size 10
tensor_range = np.arange(10, 101, 10)
print("\nTensor with values 10 to 100 (step 10):\n", tensor_range)

Identity Matrix (5x5):
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Tensor filled with 7s (4x4):
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]

Diagonal Matrix with [1,2,3,4]:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

Tensor with values 10 to 100 (step 10):
 [ 10  20  30  40  50  60  70  80  90 100]
